require("core/keymaps")
require("core/options")
require("core/filetype")
require("core/colorscheme")
require("plugins/plugins")
require("plugins/cmp-config")
require("plugins/nvim-tree")
require("core/lualine")
require("mason/mason")
require("formatter/formatter")

vim.cmd("filetype off")
local my_filetype = require("core.filetype")
vim.cmd("filetype on")
