require('core/keymaps')
require('core/options')
require('core/filetype')
require('core/colorscheme')
require('plugins/plugins')
require('plugins/nvim-tree')
require('plugins/cmp-config')
require('lsp/lspconfig')
require('mason/mason')
require('flutter/flutter-tools')

