require("copilot").setup({
    filetypes = {
        javascript = true,
        typescript = true,
        typescriptreact = true,
        javascriptreact = true,
        lua = true,
        python = true,
        rust = true,
        go = true,
        sh = true,
        yaml = true,
        json = true,
        html = true,
        css = true,
        help = true,
        gitcommit = true,
        gitrebase = true,
        hgcommit = true,
        ["*"] = false,
    },
})
